version: '3'
services:
  app:
    container_name: api
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST} 
      - DB_PORT=${DB_PORT}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - JWT_SECRET=${API_SECRET}
    build: .
    image: homeschooling:latest
    ports: 
      - 8080:8080 
    restart: on-failure
    depends_on:
      - database         
    networks:
      - database

  database:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    networks:
      - database
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database
    ports:
      - "5050:80"
    networks:
      - database
    restart: unless-stopped

networks:
  database:
    driver: bridge