version: '3'
services:
  app:
    container_name: dev-client
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    image: homeschooling/client:latest
    volumes:
      - './client:/usr/src/app'
      - './client/node_modules:/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
  
  api:
    container_name: dev-api
    environment:
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST} 
      - DB_PORT=${DB_PORT}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - JWT_SECRET=${JWT_SECRET}
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    image: homeschooling/api:latest
    ports: 
      - 4000:8080
    restart: on-failure
    depends_on:
      - database     

  database:
    image: postgres:latest
    container_name: homeschooling/database:latest
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - './database/data:/var/lib/postgresql/data'
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - database
    ports:
      - "5050:80"
    restart: unless-stopped